### ISSUE TITLE
Cannot use this Pugin because of an not defined global name

### ISSUE THREAD

**Issue by ibiBgOR** [pjdietz/rester-sublime-http-client#16]
Every time I select a line (e.g. GET http://www.telize.com/geoip/46.19.37.108) and select Rester from the Ctrl+Shift+P menu, I get the message "Unable to make request". Then I look at the consle an see this:
[Request]
GET /geoip/46.19.37.108 HTTP/1.1
Host: www.telize.com
Cache-control: no-cache
Exception in thread Thread-14:
Traceback (most recent call last):
  File ".\threading.py", line 532, in __bootstrap_inner
  File ".\rester\http.py", line 172, in run
NameError: global name 'ConnectionRefusedError' is not defined

How can I make RESTer work?

**Comment by Kronuz** [comment]
Sublime Text 2 uses Python 2 and `ConnectionRefusedError` is not defined there; instead the same condition causes an OSError with the `errno` attribute equal to `errno.ECONNREFUSED`.

https://github.com/pjdietz/rester-sublime-http-client/blob/7135e8cb9654d2629aa57d02f198a5ee53ae8eb7/rester/http.py#L191

Should be something like:
```python
        except OSError as e:
            if e.errno != errno.ECONNREFUSED:
                raise
            self.message = "Connection refused."
            self.success = False
            conn.close()
            return
````
